/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { DesignTokens } from '../lib/design-system';
import { Page } from '../lib/version-control';

export interface ExportOptions {
  format: 'html' | 'react' | 'nextjs' | 'vue' | 'zip';
  minifyHTML: boolean;
  minifyCSS: boolean;
  minifyJS: boolean;
  inlineResources: boolean;
  includeSEO: boolean;
  includePWA: boolean;
}

export function generateSitemap(pages: Page[], appUrl: string): string {
  const url = appUrl || "https://siteforge.netlify.app";
  const dateStr = new Date().toISOString().split('T')[0];
  const urlEntries = pages.map(p => {
    const pPath = p.isHomepage ? "" : `/${p.name.toLowerCase().replace(/\s+/g, '-')}`;
    return `
  <url>
    <loc>${url}${pPath}</loc>
    <lastmod>${dateStr}</lastmod>
    <priority>${p.isHomepage ? "1.0" : "0.8"}</priority>
  </url>`.trim();
  }).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlEntries}
</urlset>`.trim();
}

export function generateRobots(appUrl: string): string {
  const url = appUrl || "https://siteforge.netlify.app";
  return `
# robots.txt generated by SiteForge
User-agent: *
Allow: /

Sitemap: ${url}/sitemap.xml
  `.trim();
}

export function generateManifest(businessName: string, primaryColor: string): string {
  return JSON.stringify({
    name: businessName || "SiteForge Web App",
    short_name: businessName?.substring(0, 12) || "SiteForge",
    description: "Production bundle generated by SiteForge Designer",
    start_url: ".",
    display: "standalone",
    background_color: "#0f0f23",
    theme_color: primaryColor || "#8b5cf6",
    icons: [
      {
        src: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="192" height="192" viewBox="0 0 24 24" fill="none" stroke="${encodeURIComponent(primaryColor)}" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><circle cx="9" cy="9" r="2"></circle><path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"></path></svg>`,
        sizes: "192x192",
        type: "image/svg+xml"
      }
    ]
  }, null, 2);
}

export function generateFaviconSVG(primaryColor: string): string {
  return `
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <rect width="100" height="100" rx="24" fill="${primaryColor || '#8b5cf6'}"/>
  <text x="50" y="68" font-family="'Inter', sans-serif" font-weight="bold" font-size="52" fill="#ffffff" text-anchor="middle">SF</text>
</svg>
  `.trim();
}

/**
 * Builds standard optimized production HTML page containing custom layouts
 */
export function buildProductionHTML(
  pages: Page[],
  tokens: DesignTokens,
  activePageId: string,
  options: ExportOptions,
  projectHostUrl = ""
): string {
  const activePage = pages.find(p => p.id === activePageId) || pages[0];
  if (!activePage) return "<!-- No active contents -->";

  // Compile CSS custom properties based on design system
  const cssVariables = `
    :root {
      --primary-color: ${tokens.primaryColor};
      --secondary-color: ${tokens.secondaryColor};
      --accent-color: ${tokens.accentColor};
      --font-family: ${tokens.fontFamily || 'sans-serif'};
      --heading-font: ${tokens.headingFont || 'sans-serif'};
      --border-radius: ${tokens.borderRadius || '12px'};
      --spacing-scale: ${tokens.spacingScale || 4}px;
      --bg-color: ${tokens.backgroundColor || '#0f0f23'};
      --text-color: ${tokens.textColor || '#e2e8f0'};
      --gradient-start: ${tokens.gradientStart || tokens.primaryColor};
      --gradient-end: ${tokens.gradientEnd || tokens.secondaryColor};
    }
  `;

  // HTML Head items
  const metaTitle = activePage.metaTitle || `${activePage.name} - Designed with SiteForge`;
  const metaDesc = activePage.metaDescription || "Production-ready website generated using SiteForge.";
  
  let html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${metaTitle}</title>
  <meta name="description" content="${metaDesc}">
  
  <!-- Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Space+Grotesk:wght@500;700&family=Outfit:wght@400;500;600;700&family=Playfair+Display:ital,wght@0,600;0,700;1,400&family=Plus+Jakarta+Sans:wght@500;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
  
  <!-- Tailwind CSS -->
  <script src="https://cdn.tailwindcss.com"></script>
  <script>
    tailwind.config = {
      theme: {
        extend: {
          borderRadius: {
            'custom': '${tokens.borderRadius || '12px'}'
          }
        }
      }
    }
  </script>

  <!-- Favicon -->
  <link rel="icon" type="image/svg+xml" href="data:image/svg+xml;utf8,${encodeURIComponent(generateFaviconSVG(tokens.primaryColor))}">
  
  <style>
    ${cssVariables}
    
    body {
      font-family: var(--font-family);
      background-color: var(--bg-color);
      color: var(--text-color);
      margin: 0;
      padding: 0;
    }
    
    h1, h2, h3, h4, h5, h6 {
      font-family: var(--heading-font);
    }
    
    /* Custom Scrollbar */
    ::-webkit-scrollbar {
      width: 8px;
    }
    ::-webkit-scrollbar-track {
      background: var(--bg-color);
    }
    ::-webkit-scrollbar-thumb {
      background: var(--primary-color);
      border-radius: 4px;
    }
    
    ${activePage.css || ''}
  </style>
</head>
<body>
  
  <!-- MAIN MOUNT CANVAS -->
  <div id="siteforge-root">
    ${activePage.html}
  </div>

  <script>
    // Universal accordions expand functionality
    document.addEventListener("DOMContentLoaded", () => {
      const accs = document.querySelectorAll("#siteforge-root h4.cursor-pointer");
      accs.forEach(acc => {
        acc.addEventListener("click", () => {
          const content = acc.nextElementSibling;
          if (content) {
            content.classList.toggle("hidden");
            const indicator = acc.querySelector("span");
            if (indicator) {
              indicator.textContent = content.classList.contains("hidden") ? "+" : "-";
            }
          }
        });
      });
    });
  </script>
</body>
</html>
  `.trim();

  // Perform minification if options state so
  if (options.minifyHTML) {
    // Remove extra linebreaks and spaces
    html = html.replace(/\s+/g, ' ');
  }

  return html;
}

/**
 * High-quality React code parsing of active elements
 */
export function buildReactComponentCode(name: string, htmlStr: string, tokens: DesignTokens): string {
  // Simple sanitizer to convert standard HTML properties (class -> className, style as string to style as object)
  let componentName = name.replace(/[^a-zA-Z0-9]/g, '');
  componentName = componentName.charAt(0).toUpperCase() + componentName.slice(1);
  
  let reactHTML = htmlStr;
  reactHTML = reactHTML.replace(/\bclass=/g, 'className=');
  reactHTML = reactHTML.replace(/\bfor=/g, 'htmlFor=');
  reactHTML = reactHTML.replace(/\bautocomplete=/g, 'autoComplete=');
  
  // Strip comments
  reactHTML = reactHTML.replace(/<!--[\s\S]*?-->/g, '');

  return `
/**
 * Generated by SiteForge Studio
 * Adaptable component with pure customized design tokens
 */

import React from 'react';

export default function ${componentName}Component() {
  const inlineTheme = {
    "--primary-color": "${tokens.primaryColor}",
    "--secondary-color": "${tokens.secondaryColor}",
    "--accent-color": "${tokens.accentColor}",
    "--font-family": "${tokens.fontFamily}",
    "--heading-font": "${tokens.headingFont}",
    "--border-radius": "${tokens.borderRadius}",
    "--bg-color": "${tokens.backgroundColor}",
    "--text-color": "${tokens.textColor}",
  } as React.CSSProperties;

  return (
    <div style={inlineTheme} className="min-h-screen">
      ${reactHTML}
    </div>
  );
}
  `.trim();
}

/**
 * Single-click virtual Netlify deployment emulator
 */
export async function simulateNetlifyDeploy(htmlContent: string): Promise<{ liveUrl: string; deployId: string }> {
  // Let's mimic a beautiful high-fidelity deployment with a 1.5s latency loader
  await new Promise(resolve => setTimeout(resolve, 1500));
  
  const randomSuffix = Math.random().toString(36).substring(2, 9);
  const liveUrl = `https://designforge-${randomSuffix}.netlify.app`;
  const deployId = `dep_${Math.random().toString(36).substring(2, 11)}`;

  return { liveUrl, deployId };
}

/**
 * High-quality Next.js Page bundle generator
 */
export function buildNextjsComponentCode(name: string, htmlStr: string, tokens: DesignTokens): string {
  let componentName = name.replace(/[^a-zA-Z0-9]/g, '');
  componentName = componentName.charAt(0).toUpperCase() + componentName.slice(1);
  
  let reactHTML = htmlStr;
  reactHTML = reactHTML.replace(/\bclass=/g, 'className=');
  reactHTML = reactHTML.replace(/\bfor=/g, 'htmlFor=');
  reactHTML = reactHTML.replace(/\bautocomplete=/g, 'autoComplete=');
  reactHTML = reactHTML.replace(/<!--[\s\S]*?-->/g, '');

  return `
/**
 * Next.js SSR Page Component generated by SiteForge Studio
 */

import React from 'react';
import Head from 'next/head';

export default function ${componentName}Page() {
  const inlineTheme = {
    "--primary-color": "${tokens.primaryColor}",
    "--secondary-color": "${tokens.secondaryColor}",
    "--accent-color": "${tokens.accentColor}",
    "--font-family": "${tokens.fontFamily}",
    "--heading-font": "${tokens.headingFont}",
    "--border-radius": "${tokens.borderRadius}",
    "--bg-color": "${tokens.backgroundColor}",
    "--text-color": "${tokens.textColor}",
  } as React.CSSProperties;

  return (
    <>
      <Head>
        <title>${name} - SiteForge Next.js Bundle</title>
        <meta name="description" content="Next.js SSR optimized bundle exported directly by SiteForge." />
      </Head>
      <div style={inlineTheme} className="min-h-screen">
        ${reactHTML}
      </div>
    </>
  );
}
  `.trim();
}

/**
 * High-quality Vue SFC (Single File Component) template generator
 */
export function buildVueComponentCode(name: string, htmlStr: string, tokens: DesignTokens): string {
  let vueHTML = htmlStr;
  vueHTML = vueHTML.replace(/<!--[\s\S]*?-->/g, '');

  return `
<!-- Vue Single File Component generated by SiteForge -->
<template>
  <div :style="customTheme" class="min-h-screen">
    ${vueHTML}
  </div>
</template>

<script setup>
import { computed } from 'vue';

const customTheme = computed(() => ({
  '--primary-color': '${tokens.primaryColor}',
  '--secondary-color': '${tokens.secondaryColor}',
  '--accent-color': '${tokens.accentColor}',
  '--font-family': '${tokens.fontFamily}',
  '--heading-font': '${tokens.headingFont}',
  '--border-radius': '${tokens.borderRadius}',
  '--bg-color': '${tokens.backgroundColor}',
  '--text-color': '${tokens.textColor}'
}));
</script>

<style scoped>
div {
  font-family: var(--font-family);
  background-color: var(--bg-color);
  color: var(--text-color);
}
h1, h2, h3, h4, h5, h6 {
  font-family: var(--heading-font);
}
</style>
  `.trim();
}
